import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Title } from "@/components/title/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Title children="Bem vindo ao Nivelamento" variant="h1" fontSize={"3rem"}/>
        <Title children="Exercícios" variant="h2" fontSize={30}/>
        {children}</body>
    </html>
  );
}
