#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

commit_msg_file=$1
commit_msg=$(cat $commit_msg_file)

pattern="^(feat|fix|revert|merge|refactor)\(.+\):\s.+\s\-\s@[a-zA-Z0-9]+(\s-\s@[a-zA-Z0-9]+)*$"
if [[ ! "$commit_msg" =~ $pattern ]]; then
  echo "error: invalid commit message format"
  exit 1
fi