name: E-acelera

on:
  pull_request:
    types:
      [
        opened,
        reopened,
        edited,
        synchronize,
        labeled,
        unlabeled,
        assigned,
        unassigned,
        review_requested,
        review_request_removed,
        ready_for_review,
        closed,
      ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Display Node.js version
        run: node -v

      - name: Display npm version
        run: npm -v

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
